import { registerInvited } from './register-invited';
import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
test('candidate selects and excludes background, detects concurrent edits and deletes the context',async({page,context})=>{
 const email=`context-${randomUUID()}@example.com`,origin='http://127.0.0.1:3000';
 const invitation=execFileSync('node',['scripts/invite.mjs',email],{encoding:'utf8'}).trim().split('\n').at(-1)!;
 expect((await registerInvited(context.request,{headers:{origin,'x-invitation-token':invitation},data:{name:'Context Test',email,password:randomUUID()+randomUUID()}})).ok()).toBeTruthy();
 const review=await (await context.request.post('/api/reviews',{headers:{origin},data:{title:'Selected background',role:'Engineer',origin:'mock'}})).json();const path=`/api/reviews/${review.id}`;
 await page.goto(`/reviews/${review.id}`);await page.locator('summary').filter({hasText:'Target role and optional background'}).click();
 await page.getByRole('textbox',{name:'Target role',exact:true}).fill('Staff engineer');await page.getByRole('textbox',{name:'Paste resume text',exact:true}).fill('I contributed to a migration.');await page.getByRole('checkbox',{name:'Use resume text in future coaching'}).check();
 await page.getByRole('textbox',{name:'Paste job description',exact:true}).fill('Looking for an engineering lead.');await page.getByRole('checkbox',{name:'Use job description in future coaching'}).check();
 let releaseSave:()=>void=()=>{};const saveGate=new Promise<void>(resolve=>{releaseSave=resolve;});let delaySave=true;
 await page.route(`**${path}/context`,async route=>{if(route.request().method()==='PUT'&&delaySave){delaySave=false;const response=await route.fetch();await saveGate;await route.fulfill({response});}else await route.continue();});
 await page.getByRole('button',{name:'Add experience story'}).click();await page.getByRole('textbox',{name:'Story 1 text'}).fill('I built an internal test tool.');await page.getByRole('button',{name:'Save context',exact:true}).click();await expect(page.getByRole('textbox',{name:'Target role',exact:true})).toBeDisabled();releaseSave();await expect(page.getByText(/Context saved/)).toBeVisible();
 await page.reload();await page.locator('summary').filter({hasText:'Target role and optional background'}).click();await expect(page.getByRole('textbox',{name:'Target role',exact:true})).toHaveValue('Staff engineer');
 await page.getByRole('checkbox',{name:'Use resume text in future coaching'}).uncheck();await page.getByRole('button',{name:'Save context',exact:true}).click();await expect(page.getByText(/Context saved/)).toBeVisible();
 const snapshot=await (await context.request.get(path+'/context')).json();expect(snapshot.context.resume.selected).toBe(false);expect(snapshot.context.stories).toHaveLength(1);
 expect((await context.request.put(path+'/context',{headers:{origin},data:{revision:snapshot.revision,context:{...snapshot.context,role:'Principal engineer'}}})).ok()).toBeTruthy();
 await page.getByRole('textbox',{name:'Target role',exact:true}).fill('Architect');await page.getByRole('button',{name:'Save context',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:/another tab|changed while saving/})).toBeVisible();
 const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.bringToFront();
 await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));
 await expect(page.getByText(/A newer context version is available/)).toBeVisible();
 await expect(page.getByRole('textbox',{name:'Target role',exact:true})).toHaveValue('Architect');await other.close();
 await context.request.delete(path,{headers:{origin},data:{}});expect((await context.request.get(path+'/context')).status()).toBe(404);
});
