import { registerInvited } from './register-invited';
import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('candidate corrects recorded wording through PATCH and keeps a draft on a concurrent edit',async({page,context})=>{
 test.setTimeout(90000);const origin='http://127.0.0.1:3000',email=`correction-${randomUUID()}@example.com`;
 const invitation=execFileSync('node',['scripts/invite.mjs',email],{encoding:'utf8'}).trim().split('\n').at(-1)!;
 const signup=await registerInvited(context.request,{headers:{origin,'x-invitation-token':invitation},data:{name:'Correction Test',email,password:randomUUID()+randomUUID()}});expect(signup.ok()).toBeTruthy();const owner=(await signup.json()).user.id;
 const review=await (await context.request.post('/api/reviews',{headers:{origin},data:{title:'Correction test',role:'Engineer',origin:'mock'}})).json();const endpoint=`/api/reviews/${review.id}`,id=randomUUID(),key=`transcripts/${review.id}/${id}.json`;
 const transcript={version:1,model:'gpt-4o-transcribe-diarize',audioSha256:'fixture',durationMs:2000,utterances:[{id:'q',speaker:'A',text:'What did you build?',startMs:0,endMs:1000,overlap:false},{id:'a',speaker:'B',text:'I built a repeated repeated café.',startMs:1000,endMs:2000,overlap:false}]};
 const folder=mkdtempSync(join(tmpdir(),'correction-fixture-'));
 try{const doc=join(folder,'transcript.json'),sql=join(folder,'seed.sql');writeFileSync(doc,JSON.stringify(transcript),{mode:0o600});execFileSync('pnpm',['exec','wrangler','r2','object','put',`interview-coach-local-media/${key}`,'--local','--file',doc],{stdio:'pipe'});writeFileSync(sql,`INSERT INTO transcriptions(id,review_id,owner_id,job_id,revision,state,result_key) VALUES('${id}','${review.id}','${owner}','${id}',1,'ready','${key}');`,{mode:0o600});execFileSync('pnpm',['exec','wrangler','d1','execute','DB','--local','--file',sql],{stdio:'pipe'});}finally{rmSync(folder,{recursive:true,force:true});}
 // Only intake presentation is fixture-backed; the transcript, corrections,
 // version conflicts, R2 snapshots and deletion use actual authenticated routes.
 await page.route(`**${endpoint}/media`,route=>route.fulfill({json:{upload:{id:'fixture',state:'admitted',name:'test.wav',parts:[]},admitted:1,reserved:0,allowance:3}}));await page.route(`**${endpoint}/processing`,route=>route.fulfill({json:{state:'ready',result:{durationMs:2000}}}));
 await page.goto(`/reviews/${review.id}`);await page.getByText('Correct this passage',{exact:true}).last().click();const editor=page.getByRole('textbox',{name:'Corrected wording',exact:true}).last();await editor.fill('I built a service 🧑🏽‍💻 at the café.');await expect(page.getByRole('button',{name:'Save correction'}).last()).toBeDisabled();await page.getByRole('checkbox',{name:'This wording reflects the recording, without adding new information.'}).last().check();await page.getByRole('button',{name:'Save correction'}).last().click();await expect(page.getByText('Correction saved. Refresh analysis when you are ready.')).toBeVisible();await expect(page.getByText('Candidate-corrected wording · original audio range retained')).toBeVisible();await expect(page.getByText('Audio covers 1–2 seconds.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh analysis',exact:true})).toBeVisible();
 const latest=await (await context.request.get(endpoint+'/transcript')).json();expect(latest.revision).toBe(2);expect(latest.transcript.utterances[1].startMs).toBe(1000);
 // An older delayed GET must not rewind the displayed transcript version.
 await page.route(`**${endpoint}/transcript`,route=>route.request().method()==='GET'?route.fulfill({json:{id,revision:1,state:'ready',transcript}}):route.continue());const staleResponse=page.waitForResponse(response=>response.url().endsWith(endpoint+'/transcript')&&response.request().method()==='GET');const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));expect((await (await staleResponse).json()).revision).toBe(1);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));await expect(page.getByText('Candidate-corrected wording · original audio range retained')).toBeVisible();await page.unroute(`**${endpoint}/transcript`);await other.close();
 expect((await context.request.patch(endpoint+'/transcript',{headers:{origin},data:{transcriptId:latest.id,utteranceId:'a',text:'Another recorded wording correction.',recordingOnly:true}})).ok()).toBeTruthy();await editor.fill('My unsaved wording draft.');await page.getByRole('button',{name:'Save correction'}).last().click();await expect(page.getByRole('alert').filter({hasText:'The transcript changed or is unavailable.'})).toBeVisible();await expect(editor).toHaveValue('My unsaved wording draft.');await page.getByRole('button',{name:'Load latest passage'}).last().click();await expect(editor).toHaveValue('Another recorded wording correction.');
 await context.request.delete(endpoint,{headers:{origin},data:{}});expect((await context.request.get(endpoint+'/transcript')).status()).toBe(404);
});
