import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';

test('invited candidate creates, reopens after sign-in, and deletes a review', async ({ page }) => {
  const email = `browser-${randomUUID()}@example.com`;
  const output = execFileSync('node', ['scripts/invite.mjs', email], { encoding: 'utf8' });
  const token = output.trim().split('\n').at(-1)!;
  await page.goto('/sign-in');
  await page.getByRole('button', { name: 'Have an invitation? Create account' }).click();
  await page.getByLabel('Name', { exact: true }).fill('Pilot Candidate');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password-123');
  await page.getByLabel('Invitation code').fill(token);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your reviews' })).toBeVisible();
  await page.getByLabel('Review title').fill('Hiring manager discussion');
  await page.getByLabel('Target role').fill('Software engineer');
  await page.getByLabel('Interview type').selectOption('hiring');
  await page.getByRole('button', { name: 'Create review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Hiring manager discussion' })).toBeVisible();
  await expect(page).toHaveURL(/\/reviews\/[a-f0-9-]{36}$/);
  const savedUrl = page.url();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Hiring manager discussion' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password-123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: /Hiring manager discussion/ }).click();
  await expect(page).toHaveURL(savedUrl);
  await expect(page.getByRole('heading', { name: 'Hiring manager discussion' })).toBeVisible();
  await page.screenshot({ path: 'test-results/review-workspace.png', fullPage: true });
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete review', exact: true }).click();
  await expect(page.getByText('No reviews yet. Create your first review to get started.')).toBeVisible();
  await page.goto(savedUrl);
  await expect(page.getByRole('alert').filter({ hasText: 'Review not found.' })).toBeVisible();
});
