import { registerInvited } from './register-invited';
import { test, expect as baseExpect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';

const expect = baseExpect.configure({timeout: process.env.E2E_PREVIEW_ORIGIN ? 30000 : 5000});
test.use({actionTimeout:30000});

test('real OpenAI transcript survives leaving the page and supports timestamped playback', async ({ page, context }) => {
  test.skip(!process.env.OPENAI_TEST_WAV, 'Explicit paid integration test requires a permitted OPENAI_TEST_WAV fixture.');
  test.setTimeout(300000);
  const email = `speech-${randomUUID()}@example.com`;
  const flags = process.env.E2E_PREVIEW_ORIGIN ? ['--remote', '--env', 'preview'] : [];
  const invitation = execFileSync('node', ['scripts/invite.mjs', email, ...flags], { encoding: 'utf8' }).trim().split('\n').at(-1)!;
  const origin = process.env.E2E_PREVIEW_ORIGIN ?? 'http://127.0.0.1:3000';
  const registration = await registerInvited(context.request, { headers: { origin, 'x-invitation-token': invitation }, data: { name: 'Synthetic Speech Test', email, password: randomUUID() + randomUUID() } });
  expect(registration.ok()).toBeTruthy();
  const creation = await context.request.post(origin + '/api/reviews', { headers: { origin }, data: { title: 'Synthetic two-speaker interview', role: 'Software engineer', origin: 'mock' } });
  expect(creation.ok()).toBeTruthy(); const review = await creation.json();
  const path = origin + '/api/reviews/' + review.id;
  try {
  const bytes = readFileSync(process.env.OPENAI_TEST_WAV!);
  const initiation = await context.request.post(path + '/media', { headers: { origin }, data: { name: 'synthetic.wav', size: bytes.length, actionId: randomUUID() } });
  const upload = await initiation.json();
  const signed = await context.request.post(path + `/uploads/${upload.id}/parts/1/sign`, { headers: { origin }, data: {} });
  const { token } = await signed.json();
  expect((await context.request.put(path + `/uploads/${upload.id}/parts/1`, { headers: { origin, 'content-type': 'application/octet-stream', 'x-part-capability': token }, data: bytes })).ok()).toBeTruthy();
  expect((await context.request.post(path + `/uploads/${upload.id}/complete`, { headers: { origin }, data: {} })).ok()).toBeTruthy();
  await page.goto('/reviews');
  await page.goto('/reviews/' + review.id);
  await expect(page.getByRole('heading', { name: 'Transcript', exact: true })).toBeVisible({ timeout: 120000 });
  await expect(page.getByRole('paragraph').filter({hasText:/event.driven service/i})).toBeVisible();
  await page.reload(); await expect(page.getByRole('heading', { name: 'Transcript', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Play passage at/ }).last().click();
  const transcript = await (await context.request.get(path + '/transcript')).json();
  expect(transcript.state).toBe('ready'); expect(transcript.transcript.utterances.length).toBeGreaterThan(0);
  const selected=await (await context.request.get(path+'/context')).json();
  expect((await context.request.put(path+'/context',{headers:{origin},data:{revision:selected.revision,context:{...selected.context,resume:{text:'I contributed to a migration with two engineers.',selected:true}}}})).ok()).toBeTruthy();
  const candidateLabel = transcript.transcript.utterances.find((u: { speaker: string | null; text:string }) => /event.driven/i.test(u.text))?.speaker ?? transcript.transcript.utterances.find((u: { speaker: string | null }) => u.speaker)?.speaker; expect(candidateLabel).toBeTruthy();
  await page.getByRole('button', { name: `Listen to Speaker ${candidateLabel}`, exact: true }).click();
  const candidate = page.getByRole('checkbox', { name: `Speaker ${candidateLabel}`, exact: true });
  await candidate.focus(); await page.keyboard.press('Space'); await expect(candidate).toBeChecked();
  await page.getByRole('button', { name: 'Confirm my voice', exact: true }).click();
  await expect(page.getByText('Your voice is confirmed.', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.reload(); await expect(page.getByRole('checkbox', { name: `Speaker ${candidateLabel}`, exact: true })).toBeChecked();
  await expect(page.getByText('Your voice is confirmed.', { exact: true })).toBeVisible();
  await expect.poll(async () => (await (await context.request.get(path + '/threads')).json())?.state, { timeout: 60000 }).toBe('ready');
  const grouped=await (await context.request.get(path + '/threads')).json();
  expect(grouped.groups.length).toBeGreaterThan(0);
  await expect(page.getByRole('heading', { name: 'Question threads', exact: true })).toBeVisible();
  await expect.poll(async () => (await (await context.request.get(path + '/coaching')).json())?.state, { timeout: 120000 }).toMatch(/^(ready|partial)$/);
  const coaching=await (await context.request.get(path + '/coaching')).json();
  expect(coaching.jobs.length).toBeGreaterThan(0);
  expect(coaching.jobs.some((job:{state:string})=>job.state==='ready')).toBe(true);
  expect(coaching.jobs.every((job:{state:string})=>['ready','withheld'].includes(job.state))).toBe(true);
  const contextBefore=await (await context.request.get(path+'/context')).json();
  const contextAfter=await (await context.request.put(path+'/context',{headers:{origin},data:{revision:contextBefore.revision,context:{...contextBefore.context,role:'Staff engineer'}}})).json();
  expect((await context.request.post(path+'/coaching',{headers:{origin},data:{actionId:randomUUID(),contextRevision:contextAfter.revision}})).ok()).toBeTruthy();
  await expect.poll(async()=> (await (await context.request.get(path+'/coaching')).json())?.state,{timeout:120000}).toMatch(/^(ready|partial)$/);
  const deletion = await context.request.delete(path, { headers: { origin }, data: {} }); expect([202,204]).toContain(deletion.status());
  expect((await context.request.get(path + '/transcript')).status()).toBe(404);
  } finally { await context.request.delete(path, {headers:{origin},data:{},timeout:10000}).catch(() => {}); }
});
