const brand = '<div class="brand"><span class="brand-mark">↗</span>Interview Coach</div>';
const btn = (label, action = 'import', primary = true) => `<button class="btn ${primary ? 'primary' : ''}" data-action="${action}">${label}</button>`;
const nav = () => `<nav class="product-nav">${brand}<div class="nav-actions"><button class="text-button" data-action="example">See an example</button><button class="text-button" data-action="dashboard">Log in</button></div></nav>`;
const appnav = (active = 'Reviews') => `<nav class="product-nav appbar">${brand}<div class="appnav">${['Reviews', 'Saved answers', 'Priorities'].map(t => `<button class="${t === active ? 'active' : ''}" data-action="${t === 'Reviews' ? 'dashboard' : t === 'Saved answers' ? 'saved' : 'priorities'}">${t}</button>`).join('')}</div><span class="avatar" aria-label="Sample user Alex">AL</span></nav>`;
const foot = '<footer class="landing-foot"><span>Interview Coach</span><span>Your experience. A more considered next answer.</span></footer>';
const sample = '<div class="sample-strip"><div><span class="sample-label">From your transcript</span><p>“We had different opinions, so we talked and agreed on a plan.”</p></div><div><span class="sample-label">A useful next step</span><p>Explain what you did to help the team reach that agreement.</p></div></div>';
const priorities = '<div class="priority-list"><h4>For your next interview</h4><div class="priority"><span class="number">01</span><span>Name your own contribution.</span></div><div class="priority"><span class="number">02</span><span>Explain why you chose that approach.</span></div><button class="text-button" data-action="priorities">View preparation priorities ↗</button></div>';
const concepts = {
  1: {
    title: 'The review library', note: 'A quiet front door and a familiar review list. Best for getting started with minimal friction.',
    landing: `${nav()}<div class="hero centered"><span class="eyebrow">MAKE YOUR LAST INTERVIEW USEFUL</span><h2>Your next answer<br>starts with your last one.</h2><p>Review an interview transcript, understand what needs more detail, and save an answer to build on.</p>${btn('Review a transcript ↗')}<small class="helper">Paste text or upload a .txt file</small></div><div class="steps"><span><i class="step-number">1</i>Add your transcript</span><span><i class="step-number">2</i>Explore suggestions</span><span><i class="step-number">3</i>Save useful answers</span></div>${sample}${foot}`,
    dashboard: `${appnav()}<div class="dashboard-pad"><div class="heading-row"><div><h3>Your interview reviews</h3><p>Pick up where you left off, or bring in another transcript.</p></div>${btn('+ New review')}</div><div class="library-grid"><section><div class="section-heading"><span>RECENT INTERVIEWS</span><span>3 reviews</span></div><div class="interview first"><div><h4>Product designer · Acme</h4><p>Sep 14 · Real interview · 6 questions</p></div>${btn('Continue →','example',false)}</div><div class="interview"><div><h4>Design collaboration</h4><p>Sep 10 · Mock interview · 5 questions</p></div><button class="text-button" data-action="example">Open ↗</button></div><div class="interview"><div><h4>Product designer · Northstar</h4><p>Sep 06 · Real interview · 4 questions</p></div><button class="text-button" data-action="example">Open ↗</button></div></section><aside>${priorities}<p class="saved-summary">4 answers saved for future preparation.<br><button class="text-button" data-action="saved">Browse saved answers →</button></p></aside></div></div>`
  },
  2: {
    title: 'The review workspace', note: 'The product leads the story. A focused workspace keeps each question beside its original answer and suggestion.',
    landing: `${nav()}<div class="split-hero"><div class="hero"><span class="eyebrow">A CLOSER LOOK AT YOUR INTERVIEW</span><h2>Find the answer<br>inside your answer.</h2><p>Go question by question through your transcript. See what to clarify, what to keep, and why.</p>${btn('Review my interview ↗')}<small class="helper">Start with a real or mock interview transcript</small></div><div class="mini-review"><div class="mini-review-top">EXAMPLE REVIEW / QUESTION 02</div><div class="mini-review-body"><h4>Tell me about a time you disagreed with your team.</h4><span class="sample-label">Your original answer</span><div class="quote">“I put both options into a prototype and walked the team through them.”</div><div class="mini-revision"><span class="sample-label">What to keep</span><p>The prototype is a concrete example of your contribution. Lead with that action.</p></div></div></div></div><div class="strip-note"><span>Original answers preserved</span><span>Suggestions linked to your words</span><span>Revisions saved separately</span></div>${foot}`,
    dashboard: `<nav class="product-nav appbar">${brand}<span class="sample-label">YOUR REVIEW WORKSPACE</span><span class="avatar">AL</span></nav><div class="workspace-shell"><aside class="sidebar"><p>YOUR INTERVIEWS</p>${btn('+ New review')}<button class="side-link active" data-action="example">Product designer · Acme<small>Sep 14 · 6 questions</small></button><button class="side-link" data-action="example">Design collaboration<small>Sep 10 · Mock interview</small></button><button class="side-link" data-action="example">Product designer · Northstar<small>Sep 06 · Real interview</small></button><div class="side-divider"><button class="side-link" data-action="saved">Saved answers ↗</button><button class="side-link" data-action="priorities">Preparation priorities ↗</button></div></aside><div class="workspace-main"><div class="heading-row"><div><h3>Product designer · Acme</h3><p>Real interview · Sep 14 · 6 question threads</p></div><span class="pill">Review ready</span></div><div class="workspace-grid"><div class="question-list"><div class="section-heading">QUESTION FLOW</div><button class="question" data-action="question" data-question="1">01 &nbsp; Tell me about yourself.<small>Role motivation</small></button><button class="question active" data-action="question" data-question="2">02 &nbsp; A disagreement with your team<small>Collaboration · 1 follow-up</small></button><button class="question" data-action="question" data-question="3">03 &nbsp; A difficult trade-off<small>Decision making</small></button></div><article class="answer-panel" id="workspace-answer">${answerMarkup(2)}</article></div></div></div>`
  },
  3: {
    title: 'The preparation notebook', note: 'An editorial landing page and a personal notebook. Saved answers and preparation priorities lead the dashboard.',
    landing: `${nav()}<div class="notebook-hero"><div class="hero"><span class="eyebrow">REFLECT. REVISE. REMEMBER.</span><h2>Leave with more<br>than a memory<br>of the interview.</h2><p>Turn your transcript into thoughtful revisions and a few clear priorities for next time.</p>${btn('Start with a transcript ↗')}<small class="helper">For interviews you’ve already had</small></div><div class="notebook"><span class="eyebrow">YOUR NEXT-INTERVIEW NOTES</span><h4>A clearer story.<br>Still your experience.</h4><div class="notebook-line"><span>01</span><span>Start with the decision you made.</span></div><div class="notebook-line"><span>02</span><span>Make your contribution specific.</span></div><div class="notebook-line"><span>03</span><span>Keep the details you can support.</span></div><div class="notebook-bottom">Saved from your interview review ↗</div></div></div><div class="quiet-benefits"><span>Review your transcript</span><span>→</span><span>Save a revised answer</span><span>→</span><span>Prepare with intention</span></div>${foot}`,
    dashboard: `${appnav('Saved answers')}<div class="notebook-dash"><div class="heading-row"><div><span class="eyebrow">YOUR PREPARATION NOTEBOOK</span><h3 style="margin-top:10px">Bring your experience into focus.</h3><p>Keep the answers and reminders you want to return to.</p></div>${btn('+ Review a transcript')}</div><div class="notebook-columns"><section><div class="section-heading">CONTINUE REFLECTING</div><article class="note-sheet"><span class="sample-label">ACME / COLLABORATION</span><h4>A disagreement with your team</h4><p>Your prototype gives this story a clear action. Put your contribution at the center of the answer.</p>${btn('Continue this review →','example',false)}</article><div class="latest"><div class="section-heading">LATEST INTERVIEW</div><div class="answer-row"><div><p>Product designer · Acme</p><small>Sep 14 · 6 questions</small></div><button class="text-button" data-action="example">Open ↗</button></div></div></section><aside><div class="section-heading"><span>SAVED ANSWERS</span><span>4 total</span></div><div class="answer-row"><div><p>Working through disagreement</p><small>Revised draft · Acme</small></div><button class="text-button" data-action="saved">Read ↗</button></div><div class="answer-row"><div><p>Choosing between two approaches</p><small>Revised draft · Mock interview</small></div><button class="text-button" data-action="saved">Read ↗</button></div><button class="text-button" data-action="saved">All saved answers →</button><div class="notebook-priorities"><h4>Remember for next time</h4><p>01 &nbsp; Name your own contribution.</p><p>02 &nbsp; Explain the reasoning behind your decision.</p><button class="text-button" data-action="priorities">Edit priorities ↗</button></div></aside></div></div>`
  }
};
function answerMarkup(n) {
 const questions = {1:['Tell me about yourself.','I’m a product designer. Most recently I worked on onboarding for a small software team.','Start with the work that is most relevant to the role.','I’m a product designer with recent experience working on onboarding for a small software team.'],2:['Tell me about a time you disagreed with your team.','We had different opinions. I put both options into a prototype and walked the team through them. Then we agreed on a plan.','Lead with your action. The prototype makes your contribution concrete.','When our team disagreed on an approach, I put both options into a prototype and walked the team through them. We then agreed on a plan.'],3:['Tell me about a difficult trade-off.','We could ship quickly or test another option. I suggested testing because we still had questions about the flow.','Keep your reasoning visible; the uncertainty explains your recommendation.','I suggested testing another option before shipping because we still had unanswered questions about the flow.']};
 const q = questions[n];
 return `<span class="eyebrow">QUESTION 0${n} / ${n===2?'COLLABORATION':'INTERVIEW REVIEW'}</span><h4>${q[0]}</h4><div class="answer-block"><span class="sample-label">Original answer</span><p>“${q[1]}”</p></div><div class="answer-block"><span class="sample-label">Why this suggestion</span><p>${q[2]}</p></div><div class="answer-block revised"><span class="sample-label">Proposed future answer</span><p>“${q[3]}”</p></div><div class="actions">${btn('Save answer','save')}<button class="text-button" data-action="source" data-question="${n}">View source ↗</button></div>`;
}
let concept = 1;
let view = 'both';
function render(){
 document.getElementById('concept-note').textContent = concepts[concept].note;
 document.getElementById('screens').innerHTML = ['landing','dashboard'].map((s,i)=>`<section class="screen-section" data-screen="${s}" ${view!=='both'&&view!==s?'hidden':''}><div class="screen-label"><span>0${concept} / ${s==='landing'?'LANDING PAGE':'DASHBOARD'}</span><span>${i?'RETURNING USER · SAMPLE DATA':'FIRST VISIT'}</span></div><div class="screen"><div class="browser-bar"><i></i><i></i><i></i><span>interviewcoach / ${s==='landing'?'home':s}</span></div>${concepts[concept][s]}</div></section>`).join('');
 document.querySelectorAll('[data-concept]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.concept)===concept)));
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
}
function showDialog(html){document.getElementById('dialog-content').innerHTML=html;const d=document.getElementById('detail');if(!d.open)d.showModal();}
document.addEventListener('click', e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.concept){concept=Number(b.dataset.concept);render();return;}
 if(b.dataset.view){view=b.dataset.view;render();return;}
 const action=b.dataset.action;
 if(action==='dashboard'){view='dashboard';render();}
 if(action==='question'){document.getElementById('workspace-answer').innerHTML=answerMarkup(Number(b.dataset.question));document.querySelectorAll('.question').forEach(q=>q.classList.toggle('active',q===b));}
 if(action==='example')showDialog(`<h3>A closer look at one answer</h3><p>Sample review · Product designer · Acme</p>${answerMarkup(2)}`);
 if(action==='import')showDialog('<h3>Bring in an interview</h3><p>Wireframe preview — this form does not upload or analyze data.</p><label for="role">Target role</label><input id="role" placeholder="e.g. Product designer"><label for="origin">Interview type</label><select id="origin"><option>Real interview</option><option>Mock interview</option></select><label for="transcript">Paste your transcript</label><textarea id="transcript" placeholder="Interviewer: Tell me about a time…&#10;You: …"></textarea><label for="transcript-file">Or choose a plain-text file</label><input id="transcript-file" type="file" accept=".txt,text/plain"><button class="btn primary" data-action="preview">View sample review →</button>');
 if(action==='preview')showDialog(`<h3>Sample interview review</h3><p>This is illustrative content; your input has not been processed.</p>${answerMarkup(2)}`);
 if(action==='save'){b.textContent='Saved ✓';b.disabled=true;b.insertAdjacentHTML('afterend','<span class="toast" role="status">Saved for this preview.</span>');}
 if(action==='source'){
 const panel=b.closest('article') || document.getElementById('dialog-content');
 const heading=panel.querySelector('h4').textContent;
 const original=panel.querySelector('.answer-block p').textContent;
 showDialog(`<h3>Original transcript passage</h3><p>Sample transcript · Question ${b.dataset.question}</p><blockquote><strong>Interviewer:</strong> ${heading}<br><br><strong>You:</strong> ${original}</blockquote><p>Source text stays separate from proposed future answers.</p>`);
 }
 if(action==='saved')showDialog('<h3>Saved answers</h3><p>Proposed future answers · Sample content</p><div class="answer-row"><p>Working through disagreement</p></div><blockquote>When our team disagreed on an approach, I put both options into a prototype and walked the team through them. We then agreed on a plan.</blockquote><div class="answer-row"><p>Choosing between two approaches</p></div><blockquote>I suggested testing another option before shipping because we still had unanswered questions about the flow.</blockquote>');
 if(action==='priorities')showDialog('<h3>For your next interview</h3><p>Keep up to three preparation priorities. These edits are local to this preview.</p><label for="priority1">Priority 1</label><input id="priority1" value="Name your own contribution."><label for="priority2">Priority 2</label><input id="priority2" value="Explain why you chose that approach."><label for="priority3">Priority 3 · Optional</label><input id="priority3" placeholder="Add a reminder"><button class="btn primary" data-action="save">Save priorities</button>');
});
document.getElementById('close-dialog').addEventListener('click',()=>document.getElementById('detail').close());
render();
