const app=document.getElementById('app');
let page='landing',section='review',selected=1,tab='answer';
const saved=new Set();
let priorities=['Make your own contribution specific.','Explain the reasoning behind your decision.',''];
const questions=[
 {title:'Tell me about yourself.',short:'Tell me about yourself',category:'Role motivation',original:'I’m a product designer. Most recently I worked on onboarding for a small software team.',revised:'I’m a product designer with recent experience working on onboarding for a small software team.',why:'Begin with the experience that is most relevant to this role. Keep the introduction focused and leave room for a follow-up.'},
 {title:'Tell me about a time you disagreed with your team.',short:'A disagreement with your team',category:'Collaboration',original:'We had different opinions. I put both options into a prototype and walked the team through them. Then we agreed on a plan.',revised:'When our team disagreed on an approach, I put both options into a prototype and walked the team through them. We then agreed on a plan.',why:'Your prototype is a concrete example of your contribution. Leading with that action makes your role in the disagreement clearer, using only what you actually said.'},
 {title:'Tell me about a difficult trade-off.',short:'A difficult trade-off',category:'Decision making',original:'We could ship quickly or test another option. I suggested testing because we still had questions about the flow.',revised:'I suggested testing another option before shipping because we still had unanswered questions about the flow.',why:'Keep your reasoning visible. The uncertainty about the flow explains your recommendation to test before shipping.'},
 {title:'How do you work with feedback?',short:'Working with feedback',category:'Self-awareness',original:'I ask people to explain what they think isn’t working. Then I try to understand the problem before changing the design.',revised:'Before changing a design, I ask what isn’t working and try to understand the underlying problem.',why:'Preserve the sequence of your approach: understand the problem first, then consider a change. A specific example would help make this answer more concrete.'},
 {title:'Tell me about a project you are proud of.',short:'A project you are proud of',category:'Ownership',original:'I worked on onboarding. I mapped the steps and removed a duplicate screen after reviewing the flow with the team.',revised:'On an onboarding project, I mapped the steps and reviewed the flow with the team. I then removed a duplicate screen.',why:'The mapping and removal are specific actions you can keep. To explain why you are proud of this project, add an outcome you can support.'},
 {title:'Why are you interested in this role?',short:'Why this role?',category:'Role motivation',original:'I’d like to work on more complex products. I enjoy figuring out flows that have a lot of steps.',revised:'I enjoy figuring out flows with many steps, and I’d like to bring that interest to more complex products.',why:'Your interest is clear. A specific connection to this role would make it more relevant; that detail is not yet in the transcript.'}
];
const primary=(text,action)=>`<button class="btn primary" data-action="${action}">${text}<span class="arrow" aria-hidden="true">↗</span></button>`;
function landing(){return `<main class="landing"><nav class="landing-nav" aria-label="Main navigation"><span class="nav-caption">A little reflection. A clearer next answer.</span><div class="nav-links"><button class="text-btn" data-action="example">See an example</button><button class="btn small" data-page="workspace">Open workspace <span aria-hidden="true">↗</span></button></div></nav><section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span>A closer look at your interview</div><h1>Find the answer<br> inside <em>your answer.</em></h1><p>Look back at your interview. See what to clarify, what to keep, and how to tell your story next time.</p>${primary('Review my interview','import')}<div class="helper">Start with a real or mock interview transcript.</div></div><div class="demo-wrap"><article class="demo"><div class="demo-top"><span>A LOOK INSIDE YOUR REVIEW</span><span class="status"><span class="dot"></span>Example</span></div><div class="demo-body"><div class="overline">Question 02 · Collaboration</div><h2>“Tell me about a time you disagreed with your team.”</h2><div class="overline">From your original answer</div><p class="quote">“I <mark>put both options into a prototype</mark> and walked the team through them.”</p><div class="suggestion"><div class="overline">↗ &nbsp; A detail worth keeping</div><p>The prototype makes your contribution concrete. Lead with that action, then explain how the team reached a decision.</p></div></div><div class="demo-bottom"><span>Grounded in your own words</span><button class="text-btn" data-action="example">Explore this answer ↗</button></div></article></div></section><section class="how" aria-label="How it works"><div class="how-item"><span class="how-number">01</span><div><h3>Bring the conversation</h3><p>Paste a transcript from an interview you’ve already had.</p></div></div><div class="how-item"><span class="how-number">02</span><div><h3>Find what matters</h3><p>Explore each answer, with suggestions you can trace to the source.</p></div></div><div class="how-item"><span class="how-number">03</span><div><h3>Take something forward</h3><p>Save a revised answer and a few priorities for your next interview.</p></div></div></section><footer class="landing-footer"><span>Your experience. Your words. A clearer next step.</span><span>Designed for reflection, after the interview.</span></footer></main>`;}
function sidebar(){return `<aside class="sidebar"><div class="workspace-name">Your workspace<small>A place to reflect and prepare</small></div>${primary('New review','import')}<div class="review-list"><div class="side-heading">YOUR INTERVIEWS</div><button class="review-link active" data-section="review">Product designer · Acme<small>Sep 14 &nbsp; · &nbsp; 6 questions</small></button><button class="review-link" data-action="other-review">Design collaboration<small>Sep 10 &nbsp; · &nbsp; Mock interview</small></button><button class="review-link" data-action="other-review">Product designer · Northstar<small>Sep 06 &nbsp; · &nbsp; Real interview</small></button></div><div class="utility-group"><button class="utility" data-section="saved">Saved answers <span class="count">${saved.size}</span></button><button class="utility" data-section="priorities">Preparation priorities</button></div><div class="profile"><span class="avatar">AL</span><div>Alex<small>Personal workspace</small></div></div></aside>`;}
function detail(){const q=questions[selected];return `<article class="answer-detail"><div class="answer-heading"><span>QUESTION ${String(selected+1).padStart(2,'0')}</span><span>·</span><span class="tag">${q.category}</span></div><h2>${q.title}</h2><div class="answer-tabs" role="tablist" aria-label="Answer details"><button role="tab" id="answer-tab" aria-controls="answer-panel" aria-selected="${tab==='answer'}" data-tab="answer">Answer & suggestion</button><button role="tab" id="source-tab" aria-controls="answer-panel" aria-selected="${tab==='source'}" data-tab="source">Source transcript</button></div><div id="answer-panel" role="tabpanel" aria-labelledby="${tab==='answer'?'answer-tab':'source-tab'}">${tab==='answer'?`<div class="answer-columns"><section class="answer-card"><div class="card-heading">Your original answer <span aria-hidden="true">↙</span></div><p>“${q.original}”</p><p class="card-note">As recorded in your transcript</p></section><section class="answer-card proposed"><div class="card-heading">A proposed revision <span aria-hidden="true">↗</span></div><p>“${escapeHtml(q.revised)}”</p><p class="card-note">A future answer, using your existing details</p></section></div><div class="why"><span class="why-icon" aria-hidden="true">↳</span><div><h3>Why this suggestion</h3><p>${q.why}</p></div></div><div class="answer-actions"><div><button class="btn primary small" data-action="save">${saved.has(selected)?'✓ Answer saved':'Save this answer'}</button><button class="text-btn" data-action="edit">Edit revision</button></div><button class="text-btn" data-tab="source">View source ↗</button></div>${selected===1?'<details class="follow-up"><summary>1 follow-up in this conversation</summary><p><strong>Interviewer:</strong> What helped you reach an agreement?</p><p><strong>You:</strong> Seeing both options made it easier to talk about the differences.</p><p>This supports the role of the prototype, but does not establish a business outcome.</p></details>':''}`:`<div class="evidence"><div class="overline">ACME · ORIGINAL TRANSCRIPT · SAMPLE DATA</div><p><strong>Interviewer:</strong> ${q.title}</p><p><strong>You:</strong> ${q.original}</p><p class="note">Original wording is preserved. Revisions are saved separately.</p></div>`}</div></article>`;}
function review(){return `<div class="review-title"><div><h1>Product designer · Acme</h1><div class="review-meta"><span>Real interview</span><span>·</span><span>September 14, 2026</span><span>·</span><span>6 question threads</span></div></div><span class="status"><span class="dot"></span>Ready to review</span></div><div class="workspace-grid"><aside><div class="question-heading"><span>QUESTION FLOW</span><span>06</span></div><div class="question-list">${questions.map((q,i)=>`<button class="question ${selected===i?'active':''}" data-question="${i}" aria-pressed="${selected===i}"><span class="num">${String(i+1).padStart(2,'0')}</span><span>${q.short}<small>${q.category}${i===1?' · 1 follow-up':''}</small></span></button>`).join('')}</div><div class="questions-footer"><p>One conversation.<br>A few useful things to take forward.</p><button class="text-btn" data-section="priorities">Your preparation priorities ↗</button></div></aside>${detail()}</div>`;}
function collection(){if(section==='saved')return `<section class="empty-page"><h1>Saved answers</h1><p>Revised drafts to return to before your next conversation.</p>${saved.size?[...saved].map(i=>`<article class="saved-item"><h2>${questions[i].title}</h2><p>${escapeHtml(questions[i].revised)}</p><small>Acme · Proposed future answer</small></article>`).join(''):'<div class="evidence"><h3>Keep an answer worth returning to.</h3><p>Save a revision from your interview review. It will appear here for the rest of this preview session.</p><button class="btn" data-section="review">Return to review ↗</button></div>'}</section>`;return `<section class="empty-page"><h1>For your next interview</h1><p>Keep up to three specific things you want to remember.</p><form id="priorities-form">${priorities.map((p,i)=>`<label class="priority-input">Priority ${i+1}${i===2?' · Optional':''}<input name="priority${i}" value="${escapeHtml(p)}"></label>`).join('')}<button class="btn primary" type="submit">Save priorities</button><p class="note">Changes last for this preview session.</p></form></section>`;}
function render(){app.innerHTML=page==='landing'?landing():`<main class="app-shell">${sidebar()}<section class="workspace-content"><header class="workspace-top"><div class="breadcrumb"><span>Your interviews</span><span>/</span><span>${section==='review'?'Acme':section==='saved'?'Saved answers':'Priorities'}</span></div><button class="text-btn" data-action="prototype-note">Sample workspace ⓘ</button></header><div class="workspace-body">${section==='review'?review():collection()}</div></section></main>`;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.page===page)));}
function escapeHtml(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
const modal=document.getElementById('modal');
function openModal(content){document.getElementById('modal-body').innerHTML=content;modal.showModal();}
let toastTimer;
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),3500);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.classList.contains('close')){modal.close();return;}if(b.dataset.page){page=b.dataset.page;render();window.scrollTo(0,0);}if(b.dataset.section){page='workspace';section=b.dataset.section;render();}if(b.dataset.question!==undefined){selected=Number(b.dataset.question);tab='answer';render();}if(b.dataset.tab){tab=b.dataset.tab;render();}const a=b.dataset.action;
if(a==='example'){page='workspace';section='review';selected=1;tab='answer';render();window.scrollTo(0,0);}
if(a==='save'){saved.add(selected);render();toast('Answer saved to your preparation collection.');}
if(a==='import')openModal('<div class="eyebrow">A new perspective</div><h2 id="modal-title">Bring in your interview.</h2><p>In the finished product, you’ll paste or upload your transcript here. This prototype opens a sample review.</p><label for="role">Target role</label><input id="role" placeholder="e.g. Product designer"><label for="kind">Interview type</label><select id="kind"><option>Real interview</option><option>Mock interview</option></select><label for="transcript">Transcript</label><textarea id="transcript" placeholder="Interviewer: Tell me about a time…&#10;You: …"></textarea><label for="file">Or select a plain-text file</label><input id="file" type="file" accept=".txt,text/plain"><button class="btn primary" data-action="open-sample">Explore sample review ↗</button><p class="note">Nothing is uploaded or analyzed.</p>');
if(a==='open-sample'){modal.close();page='workspace';section='review';selected=1;render();window.scrollTo(0,0);}
if(a==='edit')openModal(`<h2 id="modal-title">Make it sound like you.</h2><p>Edit your proposed future answer. The original transcript stays unchanged.</p><form id="edit-form"><label for="revision">Your revision</label><textarea id="revision" required>${escapeHtml(questions[selected].revised)}</textarea><button class="btn primary" type="submit">Save revision</button></form>`);
if(a==='other-review')toast('This prototype includes the Acme interview.');
if(a==='prototype-note')openModal('<h2 id="modal-title">A space to explore.</h2><p>This high-fidelity prototype uses fictional sample content. You can switch questions, inspect the source, edit revisions, save answers, and update preparation priorities.</p><p class="note">Changes are held for this page session. No transcript processing or account sign-in is connected.</p>');
});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='edit-form'){questions[selected].revised=document.getElementById('revision').value.trim();saved.add(selected);modal.close();render();toast('Revision saved. Your original answer is unchanged.');}if(e.target.id==='priorities-form'){const data=new FormData(e.target);priorities=priorities.map((_,i)=>data.get('priority'+i).trim());toast('Preparation priorities saved for this session.');}});
render();
